"""Add Plex integration tables

Revision ID: f196f180f31c
Revises: 4274a5dfc4ad  
Create Date: 2025-09-07 02:41:29.954616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f196f180f31c'
down_revision = '4274a5dfc4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Plex integration tables
    op.create_table('table_plex_libraries',
        sa.Column('key', sa.TEXT(), nullable=False),
        sa.Column('title', sa.TEXT(), nullable=False),
        sa.Column('type', sa.TEXT(), nullable=False),
        sa.Column('agent', sa.TEXT(), nullable=True),
        sa.Column('scanner', sa.TEXT(), nullable=True),
        sa.Column('language', sa.TEXT(), nullable=True),
        sa.Column('uuid', sa.TEXT(), nullable=True),
        sa.Column('enabled', sa.INTEGER(), nullable=True, default=1),
        sa.Column('sync_enabled', sa.INTEGER(), nullable=True, default=1),
        sa.Column('last_scan', sa.DATETIME(), nullable=True),
        sa.Column('scan_interval', sa.INTEGER(), nullable=True, default=3600),
        sa.Column('created_at_timestamp', sa.DATETIME(), nullable=True),
        sa.Column('updated_at_timestamp', sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('key'),
        sa.UniqueConstraint('uuid')
    )
    
    op.create_table('table_plex_shows',
        sa.Column('plexId', sa.INTEGER(), nullable=False),
        sa.Column('plexGuid', sa.TEXT(), nullable=False),
        sa.Column('title', sa.TEXT(), nullable=False),
        sa.Column('year', sa.INTEGER(), nullable=True),
        sa.Column('imdbId', sa.TEXT(), nullable=True),
        sa.Column('tvdbId', sa.INTEGER(), nullable=True),
        sa.Column('tmdbId', sa.TEXT(), nullable=True),
        sa.Column('path', sa.TEXT(), nullable=False),
        sa.Column('overview', sa.TEXT(), nullable=True),
        sa.Column('poster', sa.TEXT(), nullable=True),
        sa.Column('fanart', sa.TEXT(), nullable=True),
        sa.Column('network', sa.TEXT(), nullable=True),
        sa.Column('status', sa.TEXT(), nullable=True),
        sa.Column('genres', sa.TEXT(), nullable=True),
        sa.Column('profileId', sa.INTEGER(), nullable=True),
        sa.Column('monitored', sa.INTEGER(), nullable=True, default=1),
        sa.Column('audio_language', sa.TEXT(), nullable=True),
        sa.Column('created_at_timestamp', sa.DATETIME(), nullable=True),
        sa.Column('updated_at_timestamp', sa.DATETIME(), nullable=True),
        sa.Column('last_scanned', sa.DATETIME(), nullable=True),
        sa.Column('plex_updated_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['profileId'], ['table_languages_profiles.profileId'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('plexId'),
        sa.UniqueConstraint('path'),
        sa.UniqueConstraint('plexGuid')
    )
    
    op.create_table('table_plex_episodes',
        sa.Column('plexId', sa.INTEGER(), nullable=False),
        sa.Column('plexShowId', sa.INTEGER(), nullable=False),
        sa.Column('plexGuid', sa.TEXT(), nullable=False),
        sa.Column('title', sa.TEXT(), nullable=False),
        sa.Column('season', sa.INTEGER(), nullable=False),
        sa.Column('episode', sa.INTEGER(), nullable=False),
        sa.Column('path', sa.TEXT(), nullable=False),
        sa.Column('overview', sa.TEXT(), nullable=True),
        sa.Column('duration', sa.INTEGER(), nullable=True),
        sa.Column('rating', sa.FLOAT(), nullable=True),
        sa.Column('directors', sa.TEXT(), nullable=True),
        sa.Column('writers', sa.TEXT(), nullable=True),
        sa.Column('missing_subtitles', sa.TEXT(), nullable=True),
        sa.Column('subtitles', sa.TEXT(), nullable=True),
        sa.Column('failedAttempts', sa.TEXT(), nullable=True),
        sa.Column('monitored', sa.INTEGER(), nullable=True, default=1),
        sa.Column('audio_language', sa.TEXT(), nullable=True),
        sa.Column('audio_codec', sa.TEXT(), nullable=True),
        sa.Column('video_codec', sa.TEXT(), nullable=True),
        sa.Column('resolution', sa.TEXT(), nullable=True),
        sa.Column('file_size', sa.BIGINT(), nullable=True),
        sa.Column('ffprobe_cache', sa.BLOB(), nullable=True),
        sa.Column('created_at_timestamp', sa.DATETIME(), nullable=True),
        sa.Column('updated_at_timestamp', sa.DATETIME(), nullable=True),
        sa.Column('last_scanned', sa.DATETIME(), nullable=True),
        sa.Column('plex_updated_at', sa.DATETIME(), nullable=True),
        sa.Column('originally_available_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['plexShowId'], ['table_plex_shows.plexId'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('plexId'),
        sa.UniqueConstraint('path'),
        sa.UniqueConstraint('plexGuid')
    )
    
    op.create_table('table_plex_movies',
        sa.Column('plexId', sa.INTEGER(), nullable=False),
        sa.Column('plexGuid', sa.TEXT(), nullable=False),
        sa.Column('title', sa.TEXT(), nullable=False),
        sa.Column('year', sa.INTEGER(), nullable=True),
        sa.Column('imdbId', sa.TEXT(), nullable=True),
        sa.Column('tmdbId', sa.TEXT(), nullable=True),
        sa.Column('path', sa.TEXT(), nullable=False),
        sa.Column('overview', sa.TEXT(), nullable=True),
        sa.Column('poster', sa.TEXT(), nullable=True),
        sa.Column('fanart', sa.TEXT(), nullable=True),
        sa.Column('duration', sa.INTEGER(), nullable=True),
        sa.Column('rating', sa.FLOAT(), nullable=True),
        sa.Column('studio', sa.TEXT(), nullable=True),
        sa.Column('genres', sa.TEXT(), nullable=True),
        sa.Column('directors', sa.TEXT(), nullable=True),
        sa.Column('writers', sa.TEXT(), nullable=True),
        sa.Column('actors', sa.TEXT(), nullable=True),
        sa.Column('profileId', sa.INTEGER(), nullable=True),
        sa.Column('monitored', sa.INTEGER(), nullable=True, default=1),
        sa.Column('missing_subtitles', sa.TEXT(), nullable=True),
        sa.Column('subtitles', sa.TEXT(), nullable=True),
        sa.Column('failedAttempts', sa.TEXT(), nullable=True),
        sa.Column('audio_language', sa.TEXT(), nullable=True),
        sa.Column('audio_codec', sa.TEXT(), nullable=True),
        sa.Column('video_codec', sa.TEXT(), nullable=True),
        sa.Column('resolution', sa.TEXT(), nullable=True),
        sa.Column('file_size', sa.BIGINT(), nullable=True),
        sa.Column('ffprobe_cache', sa.BLOB(), nullable=True),
        sa.Column('created_at_timestamp', sa.DATETIME(), nullable=True),
        sa.Column('updated_at_timestamp', sa.DATETIME(), nullable=True),
        sa.Column('last_scanned', sa.DATETIME(), nullable=True),
        sa.Column('plex_updated_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['profileId'], ['table_languages_profiles.profileId'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('plexId'),
        sa.UniqueConstraint('path'),
        sa.UniqueConstraint('plexGuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop Plex integration tables in reverse order
    op.drop_table('table_plex_movies')
    op.drop_table('table_plex_episodes')
    op.drop_table('table_plex_shows')
    op.drop_table('table_plex_libraries')
    # ### end Alembic commands ###
